cc_library(
    name = "lark-containers",
    srcs = [
        "linkedlist.c",
        "hashtable.c",
    ],
    hdrs = [
        "linkedlist.h",
        "hashtable.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//lark:lark-util",
        "//lark:lark-errors",
    ]
)
